// Demo data for when backend is not available

export const DEMO_PETS = [
  {
    id: 'demo-1',
    name: 'Max',
    breed: 'Golden Retriever',
    age: '2 years',
    size: 'Large',
    weight: '30kg',
    gender: 'male',
    city: 'Malta',
    images: ['https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=800'],
    description: 'Friendly and energetic golden retriever looking for a loving home!',
    adopted: false,
  },
  {
    id: 'demo-2',
    name: 'Luna',
    breed: 'Husky',
    age: '3 years',
    size: 'Medium',
    weight: '25kg',
    gender: 'female',
    city: 'Valletta',
    images: ['https://images.unsplash.com/photo-1568572933382-74d440642117?w=800'],
    description: 'Beautiful husky with striking blue eyes. Very playful!',
    adopted: false,
  },
  {
    id: 'demo-3',
    name: 'Charlie',
    breed: 'Labrador',
    age: '1 year',
    size: 'Large',
    weight: '28kg',
    gender: 'male',
    city: 'Sliema',
    images: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800'],
    description: 'Young and playful lab, great with kids and other dogs!',
    adopted: false,
  },
  {
    id: 'demo-4',
    name: 'Bella',
    breed: 'Beagle',
    age: '4 years',
    size: 'Small',
    weight: '12kg',
    gender: 'female',
    city: 'Gozo',
    images: ['https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=800'],
    description: 'Sweet beagle, loves long walks and cuddles!',
    adopted: false,
  },
  {
    id: 'demo-5',
    name: 'Rocky',
    breed: 'German Shepherd',
    age: '5 years',
    size: 'Large',
    weight: '35kg',
    gender: 'male',
    city: 'Mdina',
    images: ['https://images.unsplash.com/photo-1568393691622-c7ba131d63b4?w=800'],
    description: 'Loyal and protective, excellent guard dog!',
    adopted: false,
  },
]

export const DEMO_USER = {
  id: 'demo-user',
  username: 'demo_user',
  email: 'demo@pawmatch.app',
  role: 'ADOPTER',
  firstName: 'Demo',
  lastName: 'User',
  location: {
    city: 'Malta',
    country: 'Malta',
    address: 'Demo Address',
  },
}
